version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html/
    ports:
      - "8000:80"
  db:
    container_name: db
    build: './build/mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Nnrrr@123
      MYSQL_DATABASE: car
      MYSQL_USER: ntungu
      MYSQL_PASSWORD: Nnrrr@123
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - '8081:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db